### ISSUE TITLE
IOS Metal error with DotLottie when adding vello plugin

### ISSUE THREAD

**Issue by AngeloMateus** [linebender/bevy_vello#67]
Updated from v0.3.3 to 0.5.1 Lottie animations were working perfectly on IOS pre update.
Now when adding VelloPlugin, it still builds fine, but the app crashes on launch with:

-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1054: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'

The only useful thread I found on this was [this post](https://stackoverflow.com/questions/48028472/dispatch-thread-groups-error)

**Comment by simbleau** [comment]
This sounds like a bug of Vello, not bevy_vello. Perhaps bring it up with them?

**Comment by DJMcNab** [comment]
This would appear to be https://github.com/linebender/vello/pull/537#discussion_r1542568241

Can you confirm which shader this is failing on?

**Comment by AngeloMateus** [comment]
I'm not sure where I would find this, the error above is all I get from the crash, could you point me in the right direction?

**Comment by simbleau** [comment]
The error distinctly mentions a Compute error, which would point to either 1) the hardware not supporting compute, or 2) an error in a shader isn't compatible with iOS that was recently pushed.

A little bit of context here, `bevy_vello` doesn't have or use any compute shaders, but its underlying render backend `vello` does.

You can file an issue here, where this should be tracked: https://github.com/linebender/vello/issues

Once Vello updates with a bug fix, I can update bevy_vello with that patch.
