### ISSUE TITLE
Despawning entities with `VelloSceneBundle` does not refresh frame

### ISSUE THREAD

**Issue by nixon-voxell** [linebender/bevy_vello#78]
Reproduce:

1. Spawn a `VelloSceneBundle` with a basic `vello::Scene`.
2. Despawn the entity in the next frame.
3. The scene content still exists in the window.
4. Resize the window and it disappears (due to render target refresh I supposed).

**Comment by simbleau** [comment]
I can't reproduce using the same steps provided.

I added this system to the `scene` example:

```rust
fn remove(mut frame: Local<bool>, query: Query<Entity, With<VelloScene>>, mut commands: Commands) {
    if query.get_single().is_err() {
        return;
    }
    if *frame {
        commands.entity(query.single()).despawn();
    } else {
        *frame = true;
    }
}
``` 

And I see the scene for exactly 1 frame, and then nothing. I don't need to resize.

**Comment by simbleau** [comment]
> hmm that's weird, for me the entity was a child entity, and it was despawned by state scope. Something like this:
> 
> ```rust
>     commands
>         .spawn((
>             EmptyNodeBundle {
>                 style: Style {
>                     width: Val::Percent(100.0),
>                     height: Val::Percent(100.0),
>                     padding: UiRect::all(Val::Px(60.0)),
>                     justify_content: JustifyContent::Center,
>                     ..default()
>                 },
>                 ..default()
>             },
>             StateScoped(LobbyState::None),
>         ))
>         .with_children(|parent| {
>             parent.spawn(VelloSceneBundle {
>                 scene: xxx, // a renderable vello::Scene
>                 ..default()
>             });
>         });
> ```

Can you provide a minimum working example of the issue?

**Comment by nixon-voxell** [comment]
@simbleau I found the culprit, the culprit is because I set the `Camera::clear_color` as `ClearColorConfig::None`. Is this behavior expected? I wanted to overlay 2 2d cameras, what should I do? Should I set the clear color to maybe a transparent color instead?

the full code if you are curious to try it out (it doesn't need to be a state scope, but I did the testing using it):
```rs
use bevy::prelude::*;
use bevy_vello::{prelude::*, VelloPlugin};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(VelloPlugin::default())
        .init_state::<LobbyState>()
        .enable_state_scoped_entities::<LobbyState>()
        .add_systems(Startup, create_vello_scene)
        .add_systems(Update, change_state.run_if(in_state(LobbyState::None)))
        .run();
}

fn create_vello_scene(mut commands: Commands) {
    commands.spawn(Camera2dBundle {
        camera: Camera {
            clear_color: ClearColorConfig::None,
            ..default()
        },
        ..default()
    });

    let mut scene = vello::Scene::new();
    scene.fill(
        peniko::Fill::NonZero,
        kurbo::Affine::IDENTITY,
        &peniko::Brush::Solid(peniko::Color::rgb8(255, 255, 255)),
        None,
        &kurbo::Rect::from_center_size((0.0, 0.0), (100.0, 10.0)),
    );

    commands
        .spawn((
            NodeBundle {
                style: Style {
                    width: Val::Percent(100.0),
                    height: Val::Percent(100.0),
                    padding: UiRect::all(Val::Px(60.0)),
                    justify_content: JustifyContent::Center,
                    ..default()
                },
                ..default()
            },
            StateScoped(LobbyState::None),
        ))
        .with_children(|parent| {
            parent
                .spawn(NodeBundle::default())
                .insert(VelloSceneBundle {
                    scene: VelloScene::from(scene),
                    coordinate_space: CoordinateSpace::ScreenSpace,
                    ..default()
                });
        });
}

fn change_state(time: Res<Time>, mut next_lobby_state: ResMut<NextState<LobbyState>>) {
    if time.elapsed_seconds() > 2.0 {
        next_lobby_state.set(LobbyState::Joined);
    }
}

#[derive(States, Default, Debug, PartialEq, Eq, Hash, Clone, Copy)]
pub enum LobbyState {
    #[default]
    None,
    Joined,
    Left,
}
```

**Comment by nixon-voxell** [comment]
I am going to close this issue as using a transparent color as the camera's clear color works.
